module.exports = {
    UPDATE_DATA: 'UPDATE_DATA',
    UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
    UPDATE_DATA_FAILURE: 'UPDATE_DATA_FAILURE',
    ADD_TOTAL: 'ADD_TOTAL',
    ADD_TOTAL_SUCCESS: 'ADD_TOTAL_SUCCESS',
    ADD_TOTAL_FAILURE: 'ADD_TOTAL_FAILURE',
    ADD_UNALTERED_DATA: 'ADD_UNALTERED_DATA',
    ADD_UNALTERED_DATA_SUCCESS: 'ADD_UNALTERED_DATA_SUCCESS',
    ADD_UNALTERED_DATA_FAILURE: 'ADD_UNALTERED_DATA_FAILURE',
  };
  